//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sanscs.Homework.QuestionImport
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DBOutput<TIn> : IOutput<TIn>
	{
		public virtual void Output(TIn outputContent)
		{
			throw new System.NotImplementedException();
		}

	}
}

