//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sanscs.Homework.QuestionImport
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    public class GapMatchValidator<TIn> : IQuestionValidator<TIn>
	{
		public virtual ValidationMessage Validate(TIn input)
		{
			throw new System.NotImplementedException();
		}

	}
}

