//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sanscs.Homework.QuestionImport
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>Every resolver has a validator that needs to be injected to the property 'Validator' in the beginning of the lifecycle of the class</remarks>
	public interface IResolver<TIn, TOut> 
	{
		IValidator<TIn> Validator { get;set; }

		TOut Resolve(TIn input);

	}
}

