//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanscs.Homework.Model
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class cours
    {
        public cours()
        {
            this.knowledge_points = new HashSet<knowledge_points>();
        }
     [JsonIgnore] 
        public int ID { get; set; }
        public string Name { get; set; }
        public int Grades_ID { get; set; }
        public int Terms_ID { get; set; }
        [JsonIgnore]    
        public virtual grade grade { get; set; }
        [JsonIgnore]
        public virtual term term { get; set; }
       [JsonIgnore]
        public virtual ICollection<knowledge_points> knowledge_points { get; set; }
    }
}
