//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanscs.Homework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public question()
        {
            this.exam_history = new HashSet<exam_history>();
            this.tags = new HashSet<tag>();
        }
    
        public int ID { get; set; }
        public string Question_Number { get; set; }
        public bool Is_Available { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime CreatedBy { get; set; }
        public string Content { get; set; }
        public int Difficulties_ID { get; set; }
        public int Grades_ID { get; set; }
        public int Terms_ID { get; set; }
        public string Tips { get; set; }
        public string Solution { get; set; }
        public string ResourceURL { get; set; }
        public Nullable<int> Score { get; set; }
        public int Knowledge_Points_ID { get; set; }
    
        public virtual difficulty difficulty { get; set; }
        public virtual ICollection<exam_history> exam_history { get; set; }
        public virtual grade grade { get; set; }
        public virtual knowledge_points knowledge_points { get; set; }
        public virtual term term { get; set; }
        public virtual ICollection<tag> tags { get; set; }
    }
}
