//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanscs.Homework.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Validation;
    using System.Diagnostics;
    
    public partial class SanscsHomeworkPlatformdbEntities : DbContext
    {
        public SanscsHomeworkPlatformdbEntities()
            : base("name=SanscsHomeworkPlatformdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual void Commit()
        {
            try
            {
                base.SaveChanges();
            }
            catch (DbEntityValidationException dbEx)
            {
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        Trace.TraceInformation("Class: {0}, Property: {1}, Error: {2}", validationErrors.Entry.Entity.GetType().FullName,
                                      validationError.PropertyName, validationError.ErrorMessage);
                    }
                }
            }
        }
        public DbSet<@class> classes { get; set; }
        public DbSet<cours> courses { get; set; }
        public DbSet<dictionary> dictionaries { get; set; }
        public DbSet<difficulty> difficulties { get; set; }
        public DbSet<difficultyweight> difficultyweights { get; set; }
        public DbSet<exam_history> exam_history { get; set; }
        public DbSet<grade> grades { get; set; }
        public DbSet<knowledge_points> knowledge_points { get; set; }
        public DbSet<question> questions { get; set; }
        public DbSet<school> schools { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<students_experience> students_experience { get; set; }
        public DbSet<tag> tags { get; set; }
        public DbSet<term> terms { get; set; }
    }
}
