//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanscs.Homework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.exam_history = new HashSet<exam_history>();
            this.students_experience = new HashSet<students_experience>();
        }
    
        public int ID { get; set; }
        public string Alias { get; set; }
        public string Password { get; set; }
        public string First_Name { get; set; }
        public string Mid_Name { get; set; }
        public string Last_Name { get; set; }
        public int Grades_ID { get; set; }
        public int Schools_ID { get; set; }
        public int Classes_ID { get; set; }
        public int Terms_ID { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual ICollection<exam_history> exam_history { get; set; }
        public virtual grade grade { get; set; }
        public virtual school school { get; set; }
        public virtual ICollection<students_experience> students_experience { get; set; }
        public virtual term term { get; set; }
    }
}
