//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanscs.Homework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_experience
    {
        public int Students_ID { get; set; }
        public int Tags_ID { get; set; }
        public int Current_Difficulty_Level_ID { get; set; }
        public System.DateTime Last_Update_Time { get; set; }
        public int Knowledge_Points_ID { get; set; }
    
        public virtual difficulty difficulty { get; set; }
        public virtual knowledge_points knowledge_points { get; set; }
        public virtual student student { get; set; }
        public virtual tag tag { get; set; }
    }
}
