//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sanscs.Homework.QuestionImport
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;
    using Sanscs.Homework.Common.Helpers;
    using Sanscs.Homework.Common.Log;
    using Sanscs.Homework.Model.DTO;

    public class QuestionResolver : IQuestionResolver<string, QuestionDTO>
	{

        public IValidator<string> Validator
        {
            get
            {
                throw new NotImplementedException();
            }
            set
            {
                throw new NotImplementedException();
            }
        }

        public QuestionDTO Resolve(string input)
        {
            string questionType = GetTypeByString(input);
            IResolver<string, QuestionDTO> resolver = GetResolver(questionType);
            return resolver.Resolve(input);
        }
        private IResolver<string, QuestionDTO> GetResolver(string questionType)
        {
           //TODO resolver factory
            return new SingleChoiceResolver();
        }
        private string GetTypeByString(string content)
        {
            try
            {
                Match match = Regex.Match(content, RegexPool.Type);
                string result = string.Empty;
                if (match.Success)
                {
                    result = match.Groups["type"].ToString();
                }
              return  result;
            }
            catch (Exception ex)
            {
                Logger.Instance.Info("Get type error.");
                return null;
            }
        }
    }
}

