//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sanscs.Homework.QuestionImport
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    public class TextEntryResolver<TIn, TOut> : IQuestionResolver<TIn, TOut>
	{

        public IValidator<TIn> Validator
        {
            get
            {
                throw new NotImplementedException();
            }
            set
            {
                throw new NotImplementedException();
            }
        }

        public TOut Resolve(TIn input)
        {
            throw new NotImplementedException();
        }
    }
}

