//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sanscs.Homework.QuestionImport
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;
    using Sanscs.Homework.Common.Helpers;
    using Sanscs.Homework.Model.DTO;

    public class WordResolver<TIn, TOut> : IDocumentResolver<string, List<QuestionDTO>>
    {
        public IValidator<string> Validator
        {
            get
            {
                throw new NotImplementedException();
            }
            set
            {
                throw new NotImplementedException();
            }
        }

        public List<QuestionDTO> Resolve(string content)
        {
            QuestionResolver questionResolver = new QuestionResolver();
            List<QuestionDTO> questions = new List<QuestionDTO>();
            if (Validator.Validate(content).Result)
            {
                string[] queStrs = Regex.Split(content, RegexPool.Split);
                foreach (string que in queStrs)
                {
                    questions.Add(questionResolver.Resolve(que));
                }
            }
            return questions;
        }
    }
}

